### ISSUE TITLE
Rename newlines-between option to newlinesBetween

### ISSUE THREAD

**Issue by ai** [Tibfib/eslint-plugin-import-helpers#1]
Seems like cameCase is it standard for rule options in ESLint code (`allowImplicit`) and many other plugins.

We can use `newlinesBetween` together with `newlines-between` to avoid major release.

**Comment by willhoney7** [comment]
Totally agreed! This was the name of the preference coming over from [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md) (which is where I started this rule from). To reduce friction I left it as is.

There's a few things I'd like to do to clean up this rule a bit. This is one.

**Comment by willhoney7** [comment]
Closing this issue. You can track the progress in the v1 issue: #4. I'm hoping to have time this weekend to finish converting the tests and get v1 out
