### ISSUE TITLE
Support for ESLint v7?

### ISSUE THREAD

**Issue by lffg** [Tibfib/eslint-plugin-import-helpers#26]
https://github.com/Tibfib/eslint-plugin-import-helpers/blob/c939cbbdb49023912d3302c913de8177dec18151/package.json#L24

Are you planning to support the ESLint [7.x](https://eslint.org/blog/2020/05/eslint-v7.0.0-released)?

**Comment by willhoney7** [comment]
Thank you for the notice! I'll see if I can get a release out in the next week. If anyone would like to submit a PR, I can get it out a bit faster.

**Comment by roberto-souza** [comment]
Hello, do you have any predictions for ESLint 7.x support?

**Comment by willhoney7** [comment]
Hello! Apologies for the delayed response on all of this. We sold our house, moved, and things are finally starting to calm down. I'll set some time aside this week to add ESLint 7 support

**Comment by willhoney7** [comment]
I just published [v1.1.0](https://www.npmjs.com/package/eslint-plugin-import-helpers/v/1.1.0) which supports ESLint 7. I didn't see any breaking changes and tested with ESLint 5 and 6 as well.
