### ISSUE TITLE
Does not work with typescript

### ISSUE THREAD

**Issue by sobolevn** [Tibfib/eslint-plugin-import-helpers#3]
Thanks for this plugin! I have been waiting it for several years. https://github.com/wemake-services/wemake-vue-template/issues/495

Unfortunately, it does not work with `eslint` and `typescript`. 
I am using this setup: https://github.com/wemake-services/wemake-vue-template/blob/feature-typescript/template/.eslintrc.js

Whenever I shuffle imports in any file (including `.ts` and `.vue`) - nothin happens.
It just passes.

```
» npm run lint:js

> name@0.0.0 lint:js /Users/sobolev/Documents/github/wemake-vue-template/template
> eslint --ext .js,.jsx,.ts,.tsx,.vue,.json --ignore-path .gitignore .
```

Things that I have done (that are not included into the template):

1. `npm i -D eslint-plugin-import-helpers

```
+ eslint-plugin-import-helpers@0.1.3
added 3 packages from 5 contributors, removed 180 packages and audited 1503420 packages in 44.013s
found 0 vulnerabilities
```

2. `.eslintrc.js` modifications:

```js
  'plugins': [
    ...
    'import-helpers',
  ],
  'rules': {
    // import order
    'import-helpers/order-imports': 2,
    ...
```
3. Modify any of these files: https://github.com/wemake-services/wemake-vue-template/blob/feature-typescript/template/client/logics/api/comments.ts#L1-L2 or https://github.com/wemake-services/wemake-vue-template/blob/feature-typescript/template/client/components/Comment.vue#L32-L38

Am I doing something wrong?

**Comment by willhoney7** [comment]
Hi there!

This plugin does in fact work with TypeScript. You will need to configure ESLint to use the typescript parser. See here for more info: https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser

Basically, you need to add
```javascript
parser: '@typescript-eslint/parser',
parserOptions: {
	project: './tsconfig.json',
	sourceType: 'module',
},
```
to your `.eslintrc.js`. 

I honestly don't know how to get it to work with Vue. There's probably a Vue parser for ESLint. I'm guessing you can define specific parsers for specific extensions? Ie use `@typescript-eslint/parser` for .ts and .tsx files and the Vue parser for .vue files. I'm not 100% sure.
