### ISSUE TITLE
Support the latest version of ESLint (v8)

### ISSUE THREAD

**Issue by micalevisk** [Tibfib/eslint-plugin-import-helpers#42]
Can you please update the range below? I want to use this package with ESLint 8.2.0

https://github.com/Tibfib/eslint-plugin-import-helpers/blob/eedc8cda86330d4fe253a9af36d170abae03cda0/package.json#L23-L24

**Comment by willhoney7** [comment]
released with v1.2: https://github.com/Tibfib/eslint-plugin-import-helpers/releases/tag/v1.2.0
