### ISSUE TITLE
bug: node@14 requirement added as a minor 

### ISSUE THREAD

**Issue by gabrielcsapo** [Tibfib/eslint-plugin-import-helpers#51]
https://github.com/Tibfib/eslint-plugin-import-helpers/commit/49ca07b3ea169a220c2e9e36d1029bd6d1f4952e#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R27 is currently failing https://github.com/ember-template-lint/ember-template-lint CI as it supports node > 10. Is there anyway we can remove the engine requirement and make that requirement as a part of the major?

**Comment by willhoney7** [comment]
Hey! Sorry about that. I'll release a new version tonight. In the meantime, if you pin to the old version you should be able to avoid the issue.

**Comment by willhoney7** [comment]
released as 1.3.1
