### ISSUE TITLE
Some external modules being interpreted as internal modules

### ISSUE THREAD

**Issue by sprtvln** [Tibfib/eslint-plugin-import-helpers#8]
in my case it's 
`import { call, put, takeLatest } from 'redux-saga/effects';`

this is already fixed in eslint-plugin-import
https://github.com/benmosher/eslint-plugin-import/pull/794
could you please fix it your package?

**Comment by willhoney7** [comment]
Hi there!

v1 of this package will move in a different direction. There will be no concept of internal/external modules. Use regexp groups instead. This will help avoid issues like this in the future. See #4. As such, I'm going to close this. v1 is code complete, just need to finish updating the tests. I'm hoping to have time to do so soon. 

Thanks!
